# Generated by Django 3.0.6 on 2020-06-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=80)),
                ('email_usuario', models.EmailField(max_length=80)),
                ('password_usuario', models.CharField(max_length=80)),
            ],
        ),
    ]
